# _config.yml
title: "Finance Blog"
description: "A simple blog about money"
baseurl: ""
url: "https://qinyuehaothomas.github.io/Finance-Blog/"
theme: minima
plugins: [jekyll-feed, jekyll-seo-tag]

minima:
  date_format: "%Y-%m-%d"
  show_excerpts: true
