# _config.yml
title: "Finance Blog"
description: "A simple blog about money"
baseurl: ""
url: "https://qinyuehaothomas.github.io/Finance-Blog/"
theme: minima
plugins: [jekyll-feed, jekyll-seo-tag]



# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image_dir: "/assets/images/posts"
